spring.profiles.active: dev
spring:
  application:
    name: crbets-portal-api
  dataSource:
    url: "jdbc:mysql://localhost:3306/crbet_admin?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#     hibernate.ddl-auto: update
#     generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 7 
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
        shutdown-timeout: 200ms
cache:
  hit-wait: 5
  defaultExpiration: 60
  
server:
  port: 8280
  servlet:
    context-path: /crbets
    
logging:
  config: classpath:log4j2.xml

betfair:
  api:
    aping_url: https://api.betfair.com/exchange/betting
    rest_suffix: /rest/v1.0/
    timeout: 10000
    
---
spring:
  profiles: dev
  dataSource:
    url: "jdbc:mysql://gamasetdb.cjghoaa1m0um.us-east-1.rds.amazonaws.com:3306/crbet_admin_dev?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: gamasetdb
    password: '#gamasetdb2019'
  redis:
    host: localhost

---
server:
  port: 8280
spring:
  profiles: prod
  dataSource:
    url: "jdbc:mysql://gamasetdb.cjghoaa1m0um.us-east-1.rds.amazonaws.com:3306/crbet_admin_prod?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: gamasetdb
    password: '#gamasetdb2019'
  redis:
    host: crbets.yq2tnk.0001.use1.cache.amazonaws.com

